### ISSUE TITLE
Play channel and 'tick' channels

### ISSUE THREAD

**Issue by euank** [drusepth/mmorpgrps#3]
The play channel should be distinct from all 'tick' channels because it's spammy.

However, it makes sense to have multiple 'tick'/'monitor' channels in addition to the play channel.

 e.g. you could have channel `#a` and `#a-rps-info` which would both be monitored for game ticks, but the bot would only speak in the latter. This would let gameplay flow naturally with the flow of the main channel.

Commands should probably all be isolated to the play channel, apart from 'tick's.

**Comment by drusepth** [comment]
This is a great idea that could be implemented pretty easily by just making the current client's server/network configurable, rather than being hard-coded, and designating whether the client should be passive ('tick' channels) or active (play channels).

The only reason I didn't want to do this originally was that I was worried carrying game time on from channels the players were not aware of might lead to them not always staying up to date on spikes in game time (since time's not linear here), but I don't think that's actually a problem. I'd love to set up multiple play/reporting channels (e.g. across networks) and several more tick channels.

And that leads pretty intuitively into separating different "worlds" in the game, which would actually be extremely minimal changes necessary to segregate different networks into different worlds, etc.

To make chat more doable in play channels, I also wanted to throw in some color to make game output more of a grey color instead of black (like the rest of chat) -- not sure if this is a good or bad idea though.

**Comment by drusepth** [comment]
This is fixed now by specifying which channels should report game messages, and which should just tick the world.

```
    $config = {
      network:             '...',
      channels:            [
        { name: '#rps',    reporting: true  },
        { name: '#other',  reporting: false }
      ],
      nick:                'RPSGM',
```
